# Homebrew Cask for the ChordSketch desktop app.
# Auto-generated by `.github/workflows/desktop-release.yml` on
# `desktop-v*` tag pushes. Do not edit manually.
#
# Until #2075 adds Apple Developer ID signing + notarization,
# the DMG is unsigned and Gatekeeper will block launch on first
# open. The `caveats` block below tells users the exact
# quarantine-flag-clear command they need — same pattern the
# upstream Homebrew docs recommend for unsigned casks.

cask "chordsketch" do
  version "0.5.0"

  on_arm do
    sha256 "055f55495902eb833395c57f6fd0b158a1fee0f8039b0c801b364907193d687a"
    url "https://github.com/koedame/chordsketch/releases/download/desktop-v#{version}/ChordSketch_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "e5e315bb1a38fe7f239ddeb61a657c5ab1c09983b0a066124f9d0709c95fceb4"
    url "https://github.com/koedame/chordsketch/releases/download/desktop-v#{version}/ChordSketch_#{version}_x64.dmg"
  end

  name "ChordSketch"
  desc "ChordPro editor with live preview, transpose, and PDF export"
  homepage "https://github.com/koedame/chordsketch"

  # Minimum macOS matches `tauri.conf.json`'s implied baseline
  # (Tauri v2 officially supports macOS 10.15+; we floor to 12
  # because the WKWebView fixes below that version are outside
  # the project's testable surface). Note the space between `>=`
  # and `:monterey` — Homebrew Cask DSL requires it (see the
  # Cookbook at https://docs.brew.sh/Cask-Cookbook#stanza-depends_on;
  # the no-space form silently fails `brew audit`).
  depends_on macos: ">= :monterey"

  app "ChordSketch.app"

  # Unsigned bundle. Homebrew Cask clears `com.apple.quarantine`
  # automatically during install, so users who `brew install
  # --cask` can launch the app directly — no manual step needed.
  # The caveat block below is a safety net for two other paths:
  # manual DMG download from the GitHub Release (where no
  # quarantine clear happens), and setups that opt out via
  # `HOMEBREW_CASK_OPTS=--no-quarantine`. Dropped entirely once
  # #2075 lands Apple Developer ID signing + notarization.
  caveats <<~EOS
    The ChordSketch desktop bundle is not yet code-signed or notarized.

    Installed via `brew install --cask`? Homebrew clears the Gatekeeper
    quarantine flag for you and the app launches directly.

    Downloaded the .dmg manually from GitHub Releases, or ran Homebrew
    with `HOMEBREW_CASK_OPTS=--no-quarantine`? Clear the flag yourself:

      xattr -dr com.apple.quarantine "#{appdir}/ChordSketch.app"

    On macOS Sequoia you may additionally need to approve the app the
    first time it launches: System Settings → Privacy & Security →
    "Open Anyway".

    Tracking: https://github.com/koedame/chordsketch/issues/2075
  EOS

  zap trash: [
    "~/Library/Application Support/me.koeda.chordsketch.desktop",
    "~/Library/Caches/me.koeda.chordsketch.desktop",
    "~/Library/Preferences/me.koeda.chordsketch.desktop.plist",
    "~/Library/WebKit/me.koeda.chordsketch.desktop",
  ]
end
