# Homebrew Cask for the ChordSketch desktop app.
# Auto-generated by `.github/workflows/desktop-release.yml` on
# `desktop-v*` tag pushes. Do not edit manually.
#
# Until #2075 adds Apple Developer ID signing + notarization,
# the DMG is unsigned and Gatekeeper will block launch on first
# open. Homebrew leaves `com.apple.quarantine` on cask downloads
# so that Gatekeeper makes its own checks, so a `brew install
# --cask` user hits the same block as a manual DMG user. The
# `caveats` block below tells them how to get past it.

cask "chordsketch" do
  version "0.8.0"

  on_arm do
    sha256 "ecb0ce983db57d53edac8045fdf495492754bdd8c1b96d7451487ecd64a41145"

    url "https://github.com/koedame/chordsketch/releases/download/desktop-v#{version}/ChordSketch_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "11736c5606c9d549d4c9b76359729079d6d7b227120a1edc9c4164a27b558688"

    url "https://github.com/koedame/chordsketch/releases/download/desktop-v#{version}/ChordSketch_#{version}_x64.dmg"
  end

  name "ChordSketch"
  desc "ChordPro editor with live preview, transpose, and PDF export"
  homepage "https://github.com/koedame/chordsketch"

  # Minimum macOS matches `tauri.conf.json`'s implied baseline
  # (Tauri v2 officially supports macOS 10.15+; we floor to 12
  # because the WKWebView fixes below that version are outside
  # the project's testable surface). A bare symbol already means
  # "this release or newer" (see the Cookbook at
  # https://docs.brew.sh/Cask-Cookbook#stanza-depends_on), so it
  # is equivalent to the `">= :monterey"` string this stanza used
  # to carry — that string comparison form is deprecated and made
  # Homebrew warn on every read of the tap.
  depends_on macos: :monterey

  app "ChordSketch.app"

  zap trash: [
    "~/Library/Application Support/me.koeda.chordsketch.desktop",
    "~/Library/Caches/me.koeda.chordsketch.desktop",
    "~/Library/Preferences/me.koeda.chordsketch.desktop.plist",
    "~/Library/WebKit/me.koeda.chordsketch.desktop",
  ]

  # Unsigned bundle. Homebrew does not clear `com.apple.quarantine`
  # (`--no-quarantine` is gone as of Homebrew 5.1), so every install
  # path needs the manual step below on first launch. Dropped
  # entirely once #2075 lands Apple Developer ID signing +
  # notarization.
  caveats <<~EOS
    The ChordSketch desktop bundle is not yet code-signed or notarized,
    so macOS Gatekeeper blocks it the first time you open it.

    Clear the quarantine flag once after installing:

      xattr -dr com.apple.quarantine "#{appdir}/ChordSketch.app"

    Or try to open the app, then go to System Settings → Privacy &
    Security and choose "Open Anyway".

    Tracking: https://github.com/koedame/chordsketch/issues/2075
  EOS
end
