# Homebrew Cask for the jamjam desktop app.
#
# Generated by the `update-cask` job in `.github/workflows/release.yml`
# from `packaging/homebrew/jamjam.rb.template` on a `v*` tag push, and
# committed to `koedame/homebrew-tap` by that job. Edit the template,
# not the generated file.
#
# The DMG file names carry the version from `src-tauri/tauri.conf.json`,
# which is not the tag on a prerelease (`v0.1.0-rc.1` ships
# `jamjam_0.1.0_aarch64.dmg`), so the job substitutes the whole file
# name rather than building it from the cask version.

cask "jamjam" do
  version "0.1.0-rc.1"

  on_arm do
    sha256 "67bde11ec6f2340f788fe13d7db30153e4cf2b887986c6a0a5de8691a39ca2f2"

    url "https://github.com/koedame/p2paudiosession/releases/download/v#{version}/jamjam_0.1.0_aarch64.dmg"
  end
  on_intel do
    sha256 "472476533600fe863dfb004b26a816f2e0c1f422c369e3b0aad10a59e31faaba"

    url "https://github.com/koedame/p2paudiosession/releases/download/v#{version}/jamjam_0.1.0_x64.dmg"
  end

  name "jamjam"
  desc "Low-latency P2P audio communication for musicians"
  homepage "https://github.com/koedame/p2paudiosession"

  # Matches the baseline the installation guide states (macOS 11+).
  depends_on macos: :big_sur

  app "jamjam.app"

  zap trash: [
    "~/Library/Application Support/me.koeda.jamjam",
    "~/Library/Caches/me.koeda.jamjam",
    "~/Library/Preferences/me.koeda.jamjam.plist",
    "~/Library/Saved Application State/me.koeda.jamjam.savedState",
    "~/Library/WebKit/me.koeda.jamjam",
  ]

  # The bundle is neither signed nor notarized yet. `brew install
  # --cask` clears the Gatekeeper quarantine flag itself, so that
  # path launches without the "damaged / unidentified developer"
  # dialog. The caveat covers the two paths where nothing clears
  # it: a DMG downloaded by hand from the release page, and
  # `HOMEBREW_CASK_OPTS=--no-quarantine`.
  caveats <<~EOS
    jamjam is not code-signed or notarized yet.

    Installed with `brew install --cask`? Homebrew clears the quarantine
    flag for you and the app opens normally.

    Downloaded the .dmg by hand, or installed with `--no-quarantine`?
    Clear the flag yourself:

      xattr -dr com.apple.quarantine "#{appdir}/jamjam.app"

    On recent macOS you may also have to allow the app once in
    System Settings -> Privacy & Security -> "Open Anyway".
  EOS
end
