# Homebrew Cask for the jamjam desktop app.
#
# Generated by the `update-cask` job in `.github/workflows/release.yml`
# from `packaging/homebrew/jamjam.rb.template` on a `v*` tag push, and
# committed to `koedame/homebrew-tap` by that job. Edit the template,
# not the generated file.
#
# The DMG file names carry the version from `src-tauri/tauri.conf.json`,
# which is not the tag on a prerelease (`v0.1.0-rc.1` ships
# `jamjam_0.1.0_aarch64.dmg`), so the job substitutes the whole file
# name rather than building it from the cask version.

cask "jamjam" do
  version "0.1.0"

  on_arm do
    sha256 "a4a7e36a92e5b4d1b7f491666a55699daf26f15fe88837d299122259c7cb9fdd"

    url "https://github.com/koedame/jamjam-client/releases/download/v#{version}/jamjam_0.1.0_aarch64.dmg"
  end
  on_intel do
    sha256 "124d0fee418b45d47a6ebcfb18ff7c1a818ca16bb116f4dc851e3cb0e5151eac"

    url "https://github.com/koedame/jamjam-client/releases/download/v#{version}/jamjam_0.1.0_x64.dmg"
  end

  name "jamjam"
  desc "Low-latency P2P audio communication for musicians"
  homepage "https://github.com/koedame/jamjam-client"

  # Matches the baseline the installation guide states (macOS 11+).
  depends_on macos: :big_sur

  app "jamjam.app"

  zap trash: [
    "~/Library/Application Support/me.koeda.jamjam",
    "~/Library/Caches/me.koeda.jamjam",
    "~/Library/Preferences/me.koeda.jamjam.plist",
    "~/Library/Saved Application State/me.koeda.jamjam.savedState",
    "~/Library/WebKit/me.koeda.jamjam",
  ]

  # Homebrew stamps `com.apple.quarantine` on everything it downloads
  # (it only skips that with `--no-quarantine`), and a bundle that
  # Apple has not notarized opens as "jamjam.app is damaged and can't
  # be opened" once that flag is on. Clearing it here is what makes
  # `brew install --cask` land on a working app. homebrew-cask itself
  # rejects this stanza, but a personal tap may carry it.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/jamjam.app"]
  end

  caveats <<~EOS
    jamjam is not notarized by Apple yet.

    Installed with `brew install --cask`? This cask clears the Gatekeeper
    quarantine flag after installing, so the app opens normally.

    Downloaded the .dmg by hand from the release page? macOS blocks the
    first launch. On macOS 15 (Sequoia) and later, open System Settings ->
    Privacy & Security and click "Open Anyway" next to the jamjam warning
    (Control-click -> Open no longer overrides Gatekeeper as of macOS 15).
    On macOS 14 and earlier, Control-click the app in Finder and pick
    "Open". Or clear the flag yourself:

      xattr -dr com.apple.quarantine "#{appdir}/jamjam.app"
  EOS
end
