# Homebrew formula for ChordSketch.
# Auto-generated by the post-release workflow. Do not edit manually.

class Chordsketch < Formula
  desc "ChordPro file format parser and renderer"
  homepage "https://github.com/koedame/chordsketch"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koedame/chordsketch/releases/download/v0.6.0/chordsketch-v0.6.0-aarch64-apple-darwin.tar.gz"
      sha256 "34d1d498d8715c3913f86067a326fce413a084cd8611a26a1a7dea83a2f41554"
    else
      url "https://github.com/koedame/chordsketch/releases/download/v0.6.0/chordsketch-v0.6.0-x86_64-apple-darwin.tar.gz"
      sha256 "9586df1ffa5cb910f4789ab2fdba5394e1bf6599e6bf90d67e5c8eb8413d85df"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/koedame/chordsketch/releases/download/v0.6.0/chordsketch-v0.6.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "17bb44e632b676f049b03acb0111b71a093cd7c18eb22e794f5f696fb19777b2"
    else
      url "https://github.com/koedame/chordsketch/releases/download/v0.6.0/chordsketch-v0.6.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3b698e3c4d9363e374414ac259d2510293fa2088d4cfdf62ceab1206c7c8b83f"
    end
  end

  def install
    bin.install "chordsketch"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/chordsketch --version")
  end
end
