# Homebrew formula for ChordSketch.
# Auto-generated by the post-release workflow. Do not edit manually.

class Chordsketch < Formula
  desc "ChordPro file format parser and renderer"
  homepage "https://github.com/koedame/chordsketch"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koedame/chordsketch/releases/download/v0.5.0/chordsketch-v0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "52e91555c399988acf05776cacd711915e4a0ddd5a185f416a7c8f77ddb6a4a2"
    else
      url "https://github.com/koedame/chordsketch/releases/download/v0.5.0/chordsketch-v0.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "c8a5d4d4b6ed527f5706877fba641b12e0a0866aec7079d60c0bde316d0ee88f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/koedame/chordsketch/releases/download/v0.5.0/chordsketch-v0.5.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "96603819cadcac8c233fc601cdd6f4a1ea06240189542edd6ad803949822d973"
    else
      url "https://github.com/koedame/chordsketch/releases/download/v0.5.0/chordsketch-v0.5.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9fa7458d21326caecaf883f96f8d57e050b59918c6bb53a0ce83b2fdd12b020d"
    end
  end

  def install
    bin.install "chordsketch"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/chordsketch --version")
  end
end
